---
- hosts: localhost
  gather_facts: no
  roles:
    - ansible-pyats
  vars:
    pfx_db: true
  tasks:
    - name:
      set_fact:
        ansible_prefix_lists: "{{ lookup('file','db_prefix_list/localhost.yml') | from_yaml }}"

    - name: Parse IOS Prefix-list
      import_role:
        name: cisco.prefix_list_manage
      vars:
        test_prefix: '10.1.1.0/24'

