---
- name: SYS >> Create Temp Directory Per Node
  file: path={{tmp_dir}}/{{ inventory_hostname }} state=directory
  tags: always
  
- name: "Generate System Configuration"
  template:
    src: "{{ansible_network_os}}/mgmt.j2"
    dest: "{{tmp_dir}}/{{ inventory_hostname }}/00_mgmt.cfg"
  tags: mgmt

- name: "Interface Configuration"
  template:
    src: "{{ansible_network_os}}/intf.j2"
    dest: "{{tmp_dir}}/{{ inventory_hostname }}/01_intf.cfg"
  tags: intf

- name: "OSPF Configuration"
  template:
    src: "{{ansible_network_os}}/ospf.j2"
    dest: "{{tmp_dir}}/{{ inventory_hostname }}/02_ospf.cfg"
  tags: ospf

# - name: "MPLS Configuration"
#   template:
#     src: "{{ansible_network_os}}/mpls.j2"
#     dest: "{{tmp_dir}}/{{ inventory_hostname }}/03_mpls.cfg"
#   tags: mpls

- name: "BGP Configuration"
  template:
    src: "{{ansible_network_os}}/bgp.j2"
    dest: "{{tmp_dir}}/{{ inventory_hostname }}/04_bgp.cfg"
  tags: bgp

# - name: "QOS Configuration"
#   template:
#     src: "{{ansible_network_os}}/qos.j2"
#     dest: "{{tmp_dir}}/{{ inventory_hostname }}/05_qos.cfg"
#   tags: qos

# - name: "Security Configuration"
#   template:
#     src: "{{ansible_network_os}}/sec.j2"
#     dest: "{{tmp_dir}}/{{ inventory_hostname }}/05_sec.cfg"
#   tags: sec

# - name: "Routing Policy Configuration"
#   template:
#     src: "{{ansible_network_os}}/route_policy.j2"
#     dest: "{{tmp_dir}}/{{ inventory_hostname }}/06_rpl.cfg"
#   tags: rpl

# - name: "Routing Configuration for JunOS"
#   template:
#     src: "{{ansible_network_os}}/routing.j2"
#     dest: "{{tmp_dir}}/{{ inventory_hostname }}/09_routing.cfg"
#   when: ansible_network_os == 'junos'

- name: SYS >> Create Configs Folder
  file: 
    path: "{{config_dir}}"
    state: directory
  run_once: yes
  tags: always

- name: SYS >> Remove Old Assembled Config
  file: 
    path: "{{config_dir}}/{{ inventory_hostname }}.cfg"
    state: absent
  changed_when: false
  tags: always

- name: SYS >> Assemble The Final configuration
  assemble:
    src: "{{tmp_dir}}/{{ inventory_hostname }}"
    dest: "{{config_dir}}/{{ inventory_hostname }}.cfg"
  changed_when: false
  tags: always

# - name: SYS >> Remove Temp Folder
#   file: path={{tmp_dir}}  state=absent
#   run_once: yes
#   tags: always